kind: pipeline
name: default

clone:
  disable: true

steps:
- name: gitea-pages
  image: plugins/webhook
  settings:
    urls: http://server1.nicholaspease.com:11003/pages
    content_type: application/json
    template: |
      {
        "repo": "{{ repo.name }}",
        "owner": "{{ repo.owner }}",
        "branch": "master"
      }

#- name: electron-build
#  image: node
#  commands:
#  - npm install 
#  - npm exec electron-packager . AviationAssistantLink